id: I37AD7BA0
legacy_id: P009104
ocr_import_info:
  bdrc_scan_id: W1KG17199
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T22:47:35'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T09:32:51.662292+00:00'
last_modified: 2022-08-31 17:34:14.823316
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG17199
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG17199
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: པོད་ཆེན་དྲུག་གི་རྩ་བ་ཁག
statistics:
  ocr_word_mean_confidence_index: 0.9730621189215539
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG17543:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17543
      total_pages: 736
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG17543.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9731979402287113
    legacy_id: v001
  I1KG17544:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17544
      total_pages: 860
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG17544.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9729398007713613
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
