id: I37AD7BA0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T22:52:46+00:00'
last_modified: '2022-06-08T08:38:43.645566+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17199
  title: པོད་ཆེན་དྲུག་གི་རྩ་བ་ཁག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    C96C:
      image_group_id: I1KG17543
      title: ''
      total_pages: 736
      order: 1
      base_file: C96C.txt
    D5E4:
      image_group_id: I1KG17544
      title: ''
      total_pages: 860
      order: 2
      base_file: D5E4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
